apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-metrics-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
      app.kubernetes.io/instance: kong
  namespaceSelector:
    matchNames:
    - kong
  endpoints:
  - port: kong-admin
    path: /metrics
    interval: 5s