# auth-mongo.yaml

# --- StatefulSet for Auth MongoDB ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-mongo
  namespace: kindergarten-app
  labels:
    app: auth-mongo
spec:
  serviceName: "auth-mongo-svc"
  replicas: 1 
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:
        app: auth-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest 
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage-auth 
          mountPath: /data/db
        # readinessProbe & livenessProbe can be added for MongoDB
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage-auth
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi 

---
# --- Service for Auth MongoDB ---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-svc 
  namespace: kindergarten-app
  labels:
    app: auth-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo
  clusterIP: None 
  selector:
    app: auth-mongo
