# deployment/k8s/core-services/activity-log/activity-log-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-log-deployment
  namespace: kindergarten-app
  labels:
    app: activity-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-log
  template:
    metadata:
      labels:
        app: activity-log
    spec:
      containers:
        - name: activity-log-container
          image: mariuspreda/activity-log-service:latest # Your Docker Hub image
          imagePullPolicy: Always # To always pull the latest tag
          ports:
            - containerPort: 5003 # Port EXPOSEd in your Dockerfile
          env:
            - name: FLASK_APP 
              value: "app.py" 
            - name: FLASK_ENV
              value: "development"
            # JWT and Flask Secret Keys from Kubernetes Secrets
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets 
                  key: JWT_SECRET_KEY
            - name: SECRET_KEY # For Flask session or other app.config uses
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: FLASK_SECRET_KEY # Assuming you use the same key as other Flask apps
            # Environment variables for connecting to db-interact-service
            - name: DB_INTERACT_SERVICE_HOST
              value: "db-interact-svc.kindergarten-app.svc.cluster.local"
            - name: DB_INTERACT_SERVICE_PORT
              value: "5000" # The port db-interact-svc listens on
            - name: DB_INTERACT_LOG_ACTIVITY_ROUTE
              value: "/internal/activities" # Target endpoint on db-interact
          livenessProbe:
            httpGet:
              path: /health 
              port: 5003
            initialDelaySeconds: 25 # Increased delay
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health 
              port: 5003
            initialDelaySeconds: 15 # Increased delay
            periodSeconds: 20
---
# deployment/k8s/core-services/activity-log/activity-log-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: activity-log-svc
  namespace: kindergarten-app
  labels:
    app: activity-log
spec:
  type: ClusterIP
  ports:
    - port: 5003 # Port the service will be available on within the cluster
      targetPort: 5003 # Port on the activity-log-container
      protocol: TCP
      name: http
  selector:
    app: activity-log
